spring:
  profiles:
    active: local
    include:
      - domain
      - external
      - oauth

  ## OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 645953090464-mufok7b9hb7rp6h2bn317h4j56q95km0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

token:
  access_token:
    expiration_time: 604800000 #30일
  secret: secret

cloud:
  aws:
    credentials:
      accessKey: AKIAUHTKEKS3LORXUVUB
      secretKey: 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
    s3:
      bucket: myini
      path: https://myini.s3.ap-northeast-2.amazonaws.com/
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false